### ISSUE TITLE
more post display details

### ISSUE THREAD

**Issue by chphoom** [chphoom/aroundtheblock#103]
quoting liya " limiting the number of posts to 2 on the home page and doing the show spoilers"

**Comment by elaine331917** [comment]
also it'd be nice to refactor all the repetitive css into the custom-theme.scss file for organization purposes and make reusing code easier

**Comment by elaine331917** [comment]
you can limit the posts like this ```*ngFor="let post of (mePosts$ | async)?.slice(0, 2)``` but it looks kind of ugly with just two posts...
