### ISSUE TITLE
add logout to nav bar

### ISSUE THREAD

**Issue by chphoom** [chphoom/aroundtheblock#118]

**Comment by chphoom** [comment]
i can take care of this and hand it off to u to style

**Comment by chphoom** [comment]
ugly implement is done

**Comment by elaine331917** [comment]
todo: figure out how to make a drop down menu with items that link to profile, settings(edit profile), and logout

menu should open on hover of user's display name, but clicking display name should still take them to their profile page

**Comment by chphoom** [comment]
> todo: figure out how to make a drop down menu with items that link to profile, settings(edit profile), and logout
> 
> menu should open on hover of user's display name, but clicking display name should still take them to their profile page
> 
> https://material.angular.io/components/menu/examples https://stackoverflow.com/questions/53618333/how-to-open-and-close-angular-mat-menu-on-hover

damn das crazy
