### ISSUE TITLE
customize the custom style.scss / style frontend

### ISSUE THREAD

**Issue by chphoom** [chphoom/aroundtheblock#12]

**Comment by elaine331917** [comment]
https://material.angular.io/components/tooltip/overview

note to self: use this for the bookmark icons

**Comment by elaine331917** [comment]
change prompt display to look better / more dynamic

**Comment by elaine331917** [comment]
also make nav bar / other pages responsive for mobile view

**Comment by elaine331917** [comment]
make countdown a thing: 
https://javascript.plainenglish.io/implement-a-countdown-timer-with-rxjs-in-angular-3852f21a4ea0
https://stackblitz.com/edit/angular-countdown-timer-component?file=README.md

**Comment by elaine331917** [comment]
can iterate through posts now, just need to make them display like in the figma prototype as well as make it responsive like in https://www.artstation.com/?sort_by=community&dimension=all
