### ISSUE TITLE
implement tags in uploading posts

### ISSUE THREAD

**Issue by elaine331917** [chphoom/aroundtheblock#129]
- in particular, at least automatically add #weChallenge or #meChallenge to their respective posts on upload (done in #134)

**Comment by chphoom** [comment]
my team in kris jordan's class as a matinput chip grid for tags
the zip file for the component is attached
[create-post.zip](https://github.com/chphoom/aroundtheblock/files/11355108/create-post.zip)

**Comment by chphoom** [comment]
if you want to reflect the drop own menus in the prototype we could store the relevant information as "medium:someting" "type:we" "subject:idk" but then remove the part before the colon for display purposes, using string operations we can also implement filtering on search
