### ISSUE TITLE
style notifications

### ISSUE THREAD

**Issue by chphoom** [chphoom/aroundtheblock#132]
https://www.angularjswiki.com/material/menu/#creating-dynamic-menu-list-items

send help elaine

**Comment by chphoom** [comment]
just updated the branch since this replies on comment being implemented

**Comment by chphoom** [comment]
okay its like a mid implementation rn, i'd like to limit the number of notifs or something and idk if the way i represent unread vs read notifs is adequate

HOWEVER it's also in a stage whwere i can work on immplementing and testing notifications for when u have saved a current weChallenge, i'm just going to somehow generate a notification at certain milestones like 1 day left, 8 hrs left?, etc...

**Comment by elaine331917** [comment]
for some reason i can't comment on this branch?? so i can't test anything

**Comment by elaine331917** [comment]
notifs aren't showing up for me

**Comment by elaine331917** [comment]
notifications have been styled for the most part

i think bold for unread and normal for read is pretty typical so that's fine
