### ISSUE TITLE
add introduction on home page

### ISSUE THREAD

**Issue by elaine331917** [chphoom/aroundtheblock#133]
### Problem
Some users get overwhelmed upon first visiting the site, maybe because there are two different things to look at on the home page. Some users may be confused as to what the site is for.

### Solution
Add introduction block on home page with simplified intro to the website and link to about me. Maybe make this only visible to non-logged in users. Could also direct them to make an account to access certain features. Use neutral colors (the yellow)

### Specific feedback from survey:
- I think at first it feels a bit overwhelming, I think it could be cool if we know what the we challenge and me challenge is when we first arrive.
- The top page for strangers who do not have the concept or not having good understanding of this site may lose the desire of going further, may think to have a nice introduction page on top.
- Also I thought that some features were kind of hidden away - like the About page was at the bottom and I didn't find it until I spent 5 minutes looking around seeing what the site was, 
- I feel like we don’t need as much text on the home page; perhaps it’s the different type faces used in the same area that threw me off a bit. It’s not bad by any means, but it’ll did take me a second longer to figure out what I needed to look at.

**Comment by chphoom** [comment]
My dad also had the a similar reaction when looking at the site at first
