### ISSUE TITLE
add dev data to make website look full

### ISSUE THREAD

**Issue by elaine331917** [chphoom/aroundtheblock#134]
- edit challenge dev data to not repeat and match current generator model
- have at least 5 weposts and 5 meposts with titles, descriptions, tags, and comments on some of them
- have at least 5 users with profile pictures, bios, pronouns, saved challenges, and saved posts

**Comment by chphoom** [comment]
just put my shit posts in the dev data tbh

**Comment by elaine331917** [comment]
> just put my shit posts in the dev data tbh

that's what i was planning alkdsjfnakjn
