### ISSUE TITLE
create private profile page

### ISSUE THREAD

**Issue by chphoom** [chphoom/aroundtheblock#139]
for users who have private accounts their comments should show up as anonymous

**Comment by elaine331917** [comment]
didn't we say in the beginning that we shouldn't have anonymous comments so that people are held accountable for what they say

i think for private accs we could just make it so you either can't access their profile page or can't see anything on their profile

**Comment by chphoom** [comment]
> didn't we say in the beginning that we shouldn't have anonymous comments so that people are held accountable for what they say
> 
> i think for private accs we could just make it so you either can't access their profile page or can't see anything on their profile

i think what was for ppl who arent logged BUT i think this is a better idea regardless lol, i think we should make their prof pages unavailable
