### ISSUE TITLE
implement replies

### ISSUE THREAD

**Issue by chphoom** [chphoom/aroundtheblock#141]
lol

**Comment by chphoom** [comment]
okay @elaine331917 i made replies into like, quote replies bc it's the easiest way LMAO idk if u wanna change how the quote reply looks but im officially passing it on to you to style before merge

**Comment by elaine331917** [comment]
me to professor: i don't think we're gonna implement comments and notifications
keaw, like 2 days later: implements comments and notifications AND replies

**Comment by chphoom** [comment]
i will need to implement notifications for replies

**Comment by chphoom** [comment]
notifications have implemented for replies but reading notifications doesn't work and idk y.

once @elaine331917  styles replies should we consider this done, and have another issue to address reading notifs?

**Comment by chphoom** [comment]
> notifications have implemented for replies but reading notifications doesn't work and idk y.
> 
> once @elaine331917 styles replies should we consider this done, and have another issue to address reading notifs?

reading notifications should work now
