### ISSUE TITLE
change style generator to be more art-appropriate

### ISSUE THREAD

**Issue by elaine331917** [chphoom/aroundtheblock#44]

**Comment by chphoom** [comment]
create a generator on perchange.org and then seend it to me to change the backend api route

**Comment by elaine331917** [comment]
Impressionism
Avant-garde
Baroque
Cubism
Pixel Art
Expressionism
Futurism
Minimalism
Pop Art
Rococo
Surrealism
Whimsical
Composite
Abstract
Figurative
Geometric
Minimalist
Pop Art
Naturalist
Portraiture
Still Life
Urban
Classicism
Fauvism
Contemporary
Art Noveau
Art Deco

pls check if i repeated any @liyachn

**Comment by chphoom** [comment]
https://perchance.org/art-style#edit

https://grizzly-fifth-citrine.glitch.me/api?generator=art-style&list=output
