### ISSUE TITLE
generator takes a few seconds to wake up

### ISSUE THREAD

**Issue by elaine331917** [chphoom/aroundtheblock#45]
i think it takes a while to get the external apis. you have to either refresh or click multiple times to actually get a response. but after that it becomes faster.

documenting this issue but i'm not sure if there's anything we can do to fix it right now. for now focus on other parts of the website

**Comment by elaine331917** [comment]
i tried adding a loading circle thing but i couldn't get it to work properly

**Comment by chphoom** [comment]
the spirit of procrastination compels me
