### ISSUE TITLE
fix upload on deployment

### ISSUE THREAD

**Issue by chphoom** [chphoom/aroundtheblock#65]
;orfjo;wanf;oiasrjfimeconjsommalfmkl;xfr

https://stackoverflow.com/questions/32061725/save-files-into-deployed-application-folder-with-openshift
https://stackoverflow.com/questions/70109707/openshift-missing-permissions-to-create-a-file

**Comment by chphoom** [comment]
https://access.redhat.com/documentation/en-us/red_hat_openshift_container_storage/4.6/html/deploying_openshift_container_storage_in_external_mode/enabling-file-system-access-for-containers-on-red-hat-enterprise-linux-based-nodes_rhocs

**Comment by chphoom** [comment]
modify upload to takee URL

**Comment by elaine331917** [comment]
turn uploads into links instead. will need to change dev data for posts and displaying of posts in the html/css
