### ISSUE TITLE
save items front end

### ISSUE THREAD

**Issue by chphoom** [chphoom/aroundtheblock#67]

**Comment by elaine331917** [comment]
saving challenges isn't done yet

**Comment by chphoom** [comment]
> saving challenges isn't done yet

yarrrr api routes exist but no frontend inputs so just adding the buttons and displaying the items

i'm gonna unassign myself now that the backend part is done <3 good luck charlie!!!

**Comment by elaine331917** [comment]
todo: implement unsaving challenges
