### ISSUE TITLE
highlight selected wechallenge

### ISSUE THREAD

**Issue by chphoom** [chphoom/aroundtheblock#92]

**Comment by chphoom** [comment]
i'll tackle this

**Comment by elaine331917** [comment]
keaw: 
<img width="289" alt="image" src="https://user-images.githubusercontent.com/69728884/235316063-245dbfbd-3bae-43fb-bc0e-f6657f202826.png">

keaw three days later:
<img width="268" alt="image" src="https://user-images.githubusercontent.com/69728884/235316084-ddb6d0d5-3826-4958-99c5-b83ed5868a5f.png">

**Comment by chphoom** [comment]
> keaw: <img alt="image" width="289" src="https://user-images.githubusercontent.com/69728884/235316063-245dbfbd-3bae-43fb-bc0e-f6657f202826.png">
> 
> keaw three days later: <img alt="image" width="268" src="https://user-images.githubusercontent.com/69728884/235316084-ddb6d0d5-3826-4958-99c5-b83ed5868a5f.png">

shhhhhhh
